name: main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 2.6.1
