name: CV workflow

on:
  push:
    branches:
#      - main_eng_custom
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - main_eng_custom
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:      
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Conda packages
      uses: actions/cache@v4
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-
          
    - name: Install Pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc
      
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.11"
        activate-environment: buildcv
        environment-file: environment.yml

    - name: Configure conda to use cached pkgs
      run: conda config --add pkgs_dirs ~/conda_pkgs_dir

#    - name: Conda environment
#      run: conda env create --name buildcv --file environment.yml

    - name: Run Python script
      run: conda run --name buildcv bash -c "python makeCV.py --connected --token ${{ secrets.ADS_TOKEN }}"
      
    - name: Run Python script for short CV
      run: conda run --name buildcv bash -c "python makeCV.py --short"

    - name: LaTeX CV
      uses: dante-ev/latex-action@latest
      with:
        root_file: CV.tex
        compiler: pdflatex
        args: -interaction=nonstopmode -shell-escape

    - name: LaTeX publist
      uses: dante-ev/latex-action@latest
      with:
        root_file: publist.tex
        compiler: pdflatex
        args: -interaction=nonstopmode -shell-escape

    - name: LaTeX talklist
      uses: dante-ev/latex-action@latest
      with:
        root_file: talklist.tex
        compiler: pdflatex
        args: -interaction=nonstopmode -shell-escape
    
    - name: LaTeX talklist
      uses: dante-ev/latex-action@latest
      with:
        root_file: CVshort.tex
        compiler: pdflatex
        args: -interaction=nonstopmode -shell-escape
    
    - name: Prepare
      run: |
        mkdir pdfs/
        pandoc CV.tex -f latex -t gfm -o pdfs/CV.md
        pandoc publist.tex -f latex -t gfm -o pdfs/publist.md
        pandoc talklist.tex -f latex -t gfm -o pdfs/talklist.md
        pandoc CVshort.tex -f latex -t gfm -o pdfs/CVshort.md
        mv CV.pdf publist.pdf talklist.pdf CVshort.pdf pdfs/
        mv preamble.tex CV.tex metricspapers.tex metricstalks.tex parsepapers.tex parsetalks.tex publist.tex talklist.tex CVshort.tex pdfs/
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: pdfs/

  deploy:
    # Edit here if compiling multiple papers
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: pdfs/
      
      - name: move
        run: mkdir -p github_deploy && mv pdfs/*/* github_deploy
        
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
#          publish_branch: build_custom
          publish_branch: build
          force_orphan: true

