name: CV workflow

on:
  push:
    branches:
      - main
      - test-ci
  pull_request:
    branches:
      - main
      - test-ci

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up LaTeX
      uses: docker://blang/latex:ubuntu
      
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true

    - name: Create Conda environment
      run: conda env create --name buildcv --file environment.yml

    - name: Run Python script
      run: conda run --name buildcv bash -c "python makeCV.py --connected --testing --token ${{ secrets.ADS_TOKEN }}"

    - name: Run LaTeX
      run: conda run --name buildcv bash -c "python makeCV.py --compiling"

    - name: Prepare LaTeX files
      run: |
        mkdir pdfs/
        mv *pdf pdfs/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: pdfs/

