name: conda-workflow

on:
  push:
    branches:
      - main
      - test-ci
  pull_request:
    branches:
      - main
      - test-ci

jobs:
  setup_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true

      - name: Create Conda environment
        run: conda env create --name buildcv --file environment.yml

  run_script:
    runs-on: ubuntu-latest
    needs: setup_environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2

      - name: Activate Conda environment
        run: conda activate buildcv

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python my_script.py
